services:
  - type: web
    name: form-builder-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://pruthvis2004:2C8DWVeuMfKCYQ5v@cluster0.wk9kdhx.mongodb.net/formbuilder?retryWrites=true&w=majority&appName=Cluster0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        sync: false
