services:
  - type: web
    name: form-builder-backend
    env: node
    root: server
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://pruthvis2004:2C8DWVeuMfKCYQ5v@cluster0.wk9kdhx.mongodb.net/formbuilder?retryWrites=true&w=majority&appName=Cluster0
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://your-frontend-url.vercel.app
